<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <ProjectReference Include="../LegalAssistant.Messaging/LegalAssistant.Messaging.csproj" />
    <ProjectReference Include="../LegalAssistant.Infrastructure/LegalAssistant.Infrastructure.csproj" />
    <ProjectReference Include="..\LegalAssistant.Logging\LegalAssistant.Logging.csproj" />
  </ItemGroup>

</Project>
