// <auto-generated />
using LegalAssistant.Infrastructure.Db;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LegalAssistant.Infrastructure.Db.Migrations;

[DbContext(typeof(LegalAssistantDbContext))]
[Migration("20260906143000_AddEmbeddingProcessingState")]
public partial class AddEmbeddingProcessingState
{
}
